/**
 * Type definitions for the RepCue AI Assistant feature
 *
 * This file contains all TypeScript types and interfaces used by the AI workout generation feature.
 * These types ensure type safety throughout the frontend and define the contract with the backend.
 */

/**
 * User's gender selection
 */
export type Gender = 'male' | 'female' | 'other';

/**
 * User's fitness goal(s)
 */
export type FitnessGoal = 'weight_loss' | 'muscle_building' | 'health_maintenance' | 'flexibility' | 'marathon_des_sables';

/**
 * User's fitness experience level
 */
export type FitnessLevel = 'beginner' | 'intermediate' | 'advanced';

/**
 * User's preferred training time of day
 */
export type TrainingTime = 'morning' | 'afternoon' | 'evening' | 'mixed';

/**
 * User's preferred training style
 */
export type TrainingStyle = 'strength' | 'cardio' | 'balanced';

/**
 * Time availability for workout sessions
 */
export type TimeAvailability = '15-30' | '30-45' | '45-60' | '60+';

/**
 * Height measurement with unit
 */
export interface Height {
  value: number;
  unit: 'cm' | 'ft-in';
  /** For ft-in format: inches component (0-11) */
  inches?: number;
}

/**
 * Weight measurement with unit
 */
export interface Weight {
  value: number;
  unit: 'kg' | 'lbs';
}

/**
 * Screen 1 data: Basic Information
 */
export interface Screen1Data {
  gender: Gender;
  age: number;
  height: Height;
  weight: Weight;
}

/**
 * Screen 2 data: Goals & Preferences
 */
export interface Screen2Data {
  goals: FitnessGoal[]; // Changed from single goal to array of goals
  goalDuration?: number; // Duration in months to achieve goal(s)
  fitnessLevel: FitnessLevel;
  trainingTime: TrainingTime;
}

/**
 * Screen 3 data: Health & Training Style
 */
export interface Screen3Data {
  injuries: string; // Free-form text, max 500 chars
  trainingStyle: TrainingStyle;
  timeAvailability: TimeAvailability;
  saveToProfile: boolean; // Whether to save entered data to user profile
}

/**
 * Complete onboarding data combining all screens
 */
export interface OnboardingData {
  screen1: Screen1Data;
  screen2: Screen2Data;
  screen3: Screen3Data;
}

/**
 * Request payload sent to the AI workout generation Edge Function
 */
export interface AIWorkoutRequest {
  /** User's questionnaire responses */
  responses: {
    gender: Gender;
    age: number;
    height: Height;
    weight: Weight;
    goals: FitnessGoal[]; // Multiple goals support
    goalDuration?: number; // Duration in months
    fitnessLevel: FitnessLevel;
    trainingTime: TrainingTime;
    injuries: string;
    trainingStyle: TrainingStyle;
    timeAvailability: TimeAvailability;
  };
  /** User's preferred locale for response formatting */
  locale: string;
}

/**
 * Metadata about AI workout generation
 */
export interface AIWorkoutMetadata {
  /** Indicates this workout was AI-generated */
  aiGenerated: boolean;
  /** Timestamp when the workout was generated */
  generatedAt: string; // ISO 8601 format
  /** Parameters used for generation (for future reference/regeneration) */
  generationParams: {
    goals: FitnessGoal[];
    goalDuration?: number;
    fitnessLevel: FitnessLevel;
    trainingStyle: TrainingStyle;
    timeAvailability: TimeAvailability;
  };
}

/**
 * Single workout generated by AI
 * Extends the base Workout type with AI-specific metadata
 */
export interface GeneratedWorkout {
  id: string;
  name: string;
  description: string;
  exercises: Array<{
    exerciseId: string;
    order: number;
    customSets?: number;
    customReps?: number;
    customDuration?: number;
    customRestTime?: number;
  }>;
  scheduledDays?: string[];
  estimatedDuration: number; // seconds
  metadata: AIWorkoutMetadata;
}

/**
 * Response from the AI workout generation Edge Function
 */
export interface AIWorkoutResponse {
  /** Generated workouts (1-3 workouts) */
  workouts: GeneratedWorkout[];
  /** AI-generated feedback and context for the user (e.g., timeline assessment, attention points, recommendations) */
  feedback?: string;
  /** Unique identifier for this generation request (for tracking/debugging) */
  generationId: string;
}

/**
 * Validation result for form fields
 */
export interface ValidationResult {
  /** Whether the validation passed */
  isValid: boolean;
  /** Error message if validation failed */
  error?: string;
}

/**
 * Field-level validation errors for Screen 1
 */
export interface Screen1ValidationErrors {
  gender?: string;
  age?: string;
  height?: string;
  weight?: string;
}

/**
 * Field-level validation errors for Screen 2
 */
export interface Screen2ValidationErrors {
  goals?: string;
  goalDuration?: string;
  fitnessLevel?: string;
  trainingTime?: string;
}

/**
 * Field-level validation errors for Screen 3
 */
export interface Screen3ValidationErrors {
  injuries?: string;
  trainingStyle?: string;
  timeAvailability?: string;
}

/**
 * AI workout flow state
 */
export interface AIWorkoutFlowState {
  /** Current screen (1-3) */
  currentScreen: 1 | 2 | 3;
  /** Data from all screens */
  data: Partial<OnboardingData>;
  /** Validation errors for current screen */
  errors: Screen1ValidationErrors | Screen2ValidationErrors | Screen3ValidationErrors;
  /** Whether the form is currently submitting */
  isSubmitting: boolean;
  /** Error message from submission (if any) */
  submitError?: string;
}

/**
 * Error types from the AI workout service
 */
export type AIWorkoutErrorType =
  | 'network_error'
  | 'timeout'
  | 'rate_limit'
  | 'auth_required'
  | 'auth_error'
  | 'validation_error'
  | 'ai_error'
  | 'ai_service_error'
  | 'unknown_error';

/**
 * Error response from the AI workout service
 */
export interface AIWorkoutError {
  type: AIWorkoutErrorType;
  message: string;
  /** Error code from the service */
  code?: string;
  /** HTTP status code (if applicable) */
  statusCode?: number;
  /** Retry after duration in seconds (for rate limiting) */
  retryAfter?: number;
  /** Additional error details for debugging */
  details?: Record<string, unknown>;
}
