
# docker-compose.override.yml
# Place this **next to** the Supabase CLI generated file:
#   .supabase/docker/docker-compose.yml
#
# The Docker Compose spec merges this file with the base.
# Useful to tweak ports, mount extra volumes, and set resource limits on a Raspberry Pi 5.

version: "3.9"

services:
  # --- Postgres (Supabase DB) ---
  db:
    # Uncomment platform if your Pi images need explicit arch
    # platform: "linux/arm64"
    environment:
      # Increase shared buffers for a bit more performance on Pi 5 (adjust to your RAM)
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
    ports:
      # Change the host port if 54322 conflicts (left side is host)
      - "54329:5432"
    volumes:
      # Bind-mount an extra backup directory (optional)
      - ./backups/db:/backups
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: 3G
        reservations:
          cpus: "1.0"
          memory: 1G

  # --- Kong (API Gateway) ---
  kong:
    # platform: "linux/arm64"
    ports:
      # Change the host port if 54321 conflicts
      - "554321:8000"

  # --- Studio (web console) ---
  studio:
    # platform: "linux/arm64"
    ports:
      # Change the host port if 54323 conflicts
      - "54333:3000"

  # --- Inbucket (Email testing) ---
  inbucket:
    # platform: "linux/arm64"
    ports:
      # Change the host ports if you like (UI / SMTP / POP3)
      - "54334:9000"
      - "54335:2500"
      - "54336:1100"

# Optional named volumes: you can declare new ones here if needed and
# reference them above. The Supabase CLI already creates its own volumes.
volumes:
  # example:
  # db_backups:
  #   driver: local
