import logger from './logger'
/**
 * Service Worker registration utilities for RepCue PWA
 * Implements secure service worker management following OWASP guidelines
 */

export interface SWUpdateInfo {
  updateAvailable: boolean;
  registration?: ServiceWorkerRegistration;
}

export interface SWMessage {
  type: 'SW_UPDATED' | 'SW_ACTIVATED' | 'TRIGGER_VERSION_CHECK' | 'UPDATE_NOTIFICATION' | 'VERSION_INFO' | 'GET_VERSION';
  timestamp?: string;
  data?: unknown;
}

// Event callback types
type EventCallback = (...args: unknown[]) => void;

// Event emitter for service worker events
class ServiceWorkerEventEmitter {
  private listeners: Map<string, Set<EventCallback>> = new Map();

  on(event: string, callback: EventCallback): void {
    if (!this.listeners.has(event)) {
      this.listeners.set(event, new Set());
    }
    this.listeners.get(event)!.add(callback);
  }

  off(event: string, callback: EventCallback): void {
    const listeners = this.listeners.get(event);
    if (listeners) {
      listeners.delete(callback);
    }
  }

  emit(event: string, data?: unknown): void {
    const listeners = this.listeners.get(event);
    if (listeners) {
      listeners.forEach(callback => {
        try {
          callback(data);
        } catch (error) {
          logger.error(`Error in SW event listener for ${event}:`, error);
        }
      });
    }
  }
}

export const swEventEmitter = new ServiceWorkerEventEmitter();

interface BeforeInstallPromptEvent extends Event {
  readonly platforms: string[];
  readonly userChoice: Promise<{
    outcome: 'accepted' | 'dismissed';
    platform: string;
  }>;
  prompt(): Promise<void>;
}

/**
 * Register service worker and handle updates with enhanced event handling
 * Integrates with the RepCue update system for coordinated updates
 */
export const registerServiceWorker = (): Promise<SWUpdateInfo> => {
  return new Promise((resolve) => {
    // Only register service worker in production
    if (!('serviceWorker' in navigator) || import.meta.env.DEV) {
      logger.log('🔧 Service worker not registered in development mode');
      resolve({ updateAvailable: false });
      return;
    }

    // Set up service worker message listener before registration
    setupServiceWorkerMessageListener();

    window.addEventListener('load', async () => {
      try {
        logger.log('🚀 Registering service worker...');

        // Use the service worker generated by Vite PWA plugin
        const registration = await navigator.serviceWorker.register('/sw.js', {
          scope: '/',
          updateViaCache: 'none' // Always check for updates
        });

        logger.log('✅ Service worker registered successfully');

        // Enhanced update detection
        registration.addEventListener('updatefound', () => {
          const newWorker = registration.installing;

          if (newWorker) {
            logger.log('🔄 Service worker update found');
            swEventEmitter.emit('update-found', { registration, newWorker });

            newWorker.addEventListener('statechange', () => {
              logger.log(`🔄 SW state changed to: ${newWorker.state}`);

              if (newWorker.state === 'installed') {
                if (navigator.serviceWorker.controller) {
                  // New update available
                  logger.log('📦 New content available, waiting for activation');
                  swEventEmitter.emit('update-available', { registration });
                  resolve({
                    updateAvailable: true,
                    registration
                  });
                } else {
                  // Content is cached for offline use (first install)
                  logger.log('💾 Content is cached for offline use');
                  swEventEmitter.emit('first-install', { registration });
                  resolve({
                    updateAvailable: false,
                    registration
                  });
                }
              }

              if (newWorker.state === 'activated') {
                logger.log('✅ New service worker activated');
                swEventEmitter.emit('update-activated', { registration });
              }
            });
          }
        });

        // Enhanced controller change detection
        navigator.serviceWorker.addEventListener('controllerchange', () => {
          logger.log('🔄 Service worker controller changed');
          swEventEmitter.emit('controller-changed');
        });

        // Check if service worker is already controlling the page
        if (registration.active && !navigator.serviceWorker.controller) {
          logger.log('🔄 Service worker ready but not controlling, reloading...');
          window.location.reload();
        }

        // Set up periodic update checks
        setupPeriodicUpdateCheck(registration);

        resolve({
          updateAvailable: false,
          registration
        });

      } catch (error) {
        logger.error('❌ Service worker registration failed:', error);
        swEventEmitter.emit('registration-failed', { error });
        resolve({ updateAvailable: false });
      }
    });
  });
};

/**
 * Update service worker when new version is available
 * Securely handles the update process
 */
export const updateServiceWorker = (registration: ServiceWorkerRegistration): Promise<void> => {
  return new Promise((resolve, reject) => {
    if (!registration || !registration.waiting) {
      reject(new Error('No service worker waiting to update'));
      return;
    }

    const updateWorker = registration.waiting;

    // Listen for the controlling change event
    navigator.serviceWorker.addEventListener('controllerchange', () => {
  logger.log('🔄 Service worker updated successfully');
      window.location.reload();
      resolve();
    });

    // Tell the waiting service worker to skip waiting and become active
    updateWorker.postMessage({ type: 'SKIP_WAITING' });
  });
};

/**
 * Check if the app is running in standalone mode (installed as PWA)
 */
export const isStandalone = (): boolean => {
  try {
    const mediaQuery = window.matchMedia('(display-mode: standalone)');
    return mediaQuery.matches || (window.navigator as { standalone?: boolean }).standalone === true;
  } catch {
    return (window.navigator as { standalone?: boolean }).standalone === true;
  }
};

/**
 * Force refresh the PWA by clearing all caches and reloading from server
 * This bypasses all service worker caches and forces fresh content
 */
export const forceRefreshFromServer = async (): Promise<void> => {
  try {
    logger.log('🔄 Force refreshing PWA from server...');

    // Method 1: Clear all caches
    if ('caches' in window) {
      const cacheNames = await caches.keys();
      logger.log(`🗑️ Clearing ${cacheNames.length} cache(s):`, cacheNames);
      
      await Promise.all(
        cacheNames.map(cacheName => caches.delete(cacheName))
      );
      logger.log('✅ All caches cleared');
    }

    // Method 2: Unregister service worker if present
    if ('serviceWorker' in navigator) {
      const registrations = await navigator.serviceWorker.getRegistrations();
      for (const registration of registrations) {
        logger.log('🚫 Unregistering service worker:', registration.scope);
        await registration.unregister();
      }
    }

    // Method 3: Hard reload from server
    logger.log('🔃 Performing hard reload from server...');
    window.location.reload();
    
  } catch (error) {
    logger.error('❌ Force refresh failed:', error);
    // Fallback: regular hard reload
    window.location.reload();
  }
};

/**
 * Clear only PWA caches while keeping service worker active
 * Less disruptive than full force refresh
 */
export const clearPWACaches = async (): Promise<void> => {
  try {
    if ('caches' in window) {
      const cacheNames = await caches.keys();
      logger.log(`🧹 Clearing ${cacheNames.length} PWA cache(s)...`);
      
      await Promise.all(
        cacheNames.map(cacheName => caches.delete(cacheName))
      );
      
      logger.log('✅ PWA caches cleared successfully');
    }
  } catch (error) {
    logger.error('❌ Cache clearing failed:', error);
    throw error;
  }
};

/**
 * Check for and apply service worker updates immediately
 */
export const forceUpdateServiceWorker = async (): Promise<void> => {
  try {
    if (!('serviceWorker' in navigator)) {
      throw new Error('Service worker not supported');
    }

    const registration = await navigator.serviceWorker.ready;
    
    logger.log('🔍 Checking for service worker updates...');
    await registration.update();
    
    if (registration.waiting) {
      logger.log('🚀 Activating waiting service worker...');
      registration.waiting.postMessage({ type: 'SKIP_WAITING' });
      
      // Wait for controller change
      return new Promise((resolve) => {
        navigator.serviceWorker.addEventListener('controllerchange', () => {
          logger.log('✅ Service worker updated and activated');
          window.location.reload();
          resolve();
        });
      });
    } else {
      logger.log('ℹ️ No service worker updates available');
    }
  } catch (error) {
    logger.error('❌ Service worker update failed:', error);
    throw error;
  }
};

/**
 * Show install prompt for PWA
 */
export const setupInstallPrompt = (): Promise<boolean> => {
  return new Promise((resolve) => {
    let deferredPrompt: BeforeInstallPromptEvent | null = null;

    window.addEventListener('beforeinstallprompt', (e) => {
      // Prevent the mini-infobar from appearing on mobile
      e.preventDefault();
      deferredPrompt = e as BeforeInstallPromptEvent;

      logger.log('💡 PWA install prompt available');
      resolve(true);
    });

    // Handle install completion
    window.addEventListener('appinstalled', () => {
      logger.log('🎉 PWA was installed successfully');
      deferredPrompt = null;
    });

    // Timeout if no install prompt is available
    setTimeout(() => {
      if (!deferredPrompt) {
        resolve(false);
      }
    }, 3000);
  });
};

/**
 * Set up service worker message listener for communication with the custom SW
 */
const setupServiceWorkerMessageListener = (): void => {
  if (!('serviceWorker' in navigator)) {
    return;
  }

  navigator.serviceWorker.addEventListener('message', (event) => {
    const message: SWMessage = event.data;
    logger.log('📨 Received message from service worker:', message);

    switch (message.type) {
      case 'SW_UPDATED':
        logger.log('✅ Service worker updated successfully');
        swEventEmitter.emit('sw-updated', message);
        break;

      case 'SW_ACTIVATED':
        logger.log('🎯 Service worker activated and controlling all tabs');
        swEventEmitter.emit('sw-activated', message);
        break;

      case 'TRIGGER_VERSION_CHECK':
        logger.log('🔍 Service worker requesting version check');
        swEventEmitter.emit('trigger-version-check', message);
        break;

      case 'UPDATE_NOTIFICATION':
        logger.log('📬 Update notification from service worker');
        swEventEmitter.emit('update-notification', message);
        break;

      case 'VERSION_INFO':
        logger.log('ℹ️ Version info from service worker:', message.data);
        swEventEmitter.emit('version-info', message);
        break;

      default:
        logger.log('📨 Unknown message type from service worker:', message.type);
    }
  });
};

/**
 * Set up periodic update checks in coordination with the service worker
 */
const setupPeriodicUpdateCheck = (registration: ServiceWorkerRegistration): void => {
  // Check for updates every 30 minutes when the page is visible
  const checkInterval = 30 * 60 * 1000; // 30 minutes

  const checkForUpdates = async () => {
    if (document.hidden) {
      return; // Don't check when page is hidden
    }

    try {
      logger.log('🔍 Performing periodic service worker update check...');
      await registration.update();
    } catch (error) {
      logger.error('❌ Periodic update check failed:', error);
    }
  };

  // Set up interval
  const intervalId = setInterval(checkForUpdates, checkInterval);

  // Clear interval when page is unloaded
  window.addEventListener('beforeunload', () => {
    clearInterval(intervalId);
  });

  // Also check when page becomes visible
  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) {
      // Delay slightly to avoid conflicts with other visibility handlers
      setTimeout(checkForUpdates, 1000);
    }
  });
};

/**
 * Send message to service worker
 */
export const sendMessageToServiceWorker = async (message: Partial<SWMessage>): Promise<unknown> => {
  if (!('serviceWorker' in navigator)) {
    throw new Error('Service worker not supported');
  }

  const registration = await navigator.serviceWorker.ready;

  if (!registration.active) {
    throw new Error('No active service worker');
  }

  return new Promise((resolve, reject) => {
    const messageChannel = new MessageChannel();

    messageChannel.port1.onmessage = (event) => {
      resolve(event.data);
    };

    // Timeout after 5 seconds
    const timeout = setTimeout(() => {
      reject(new Error('Service worker message timeout'));
    }, 5000);

    messageChannel.port1.onmessage = (event) => {
      clearTimeout(timeout);
      resolve(event.data);
    };

    registration.active!.postMessage(message, [messageChannel.port2]);
  });
};

/**
 * Get version information from service worker
 */
export const getServiceWorkerVersion = async (): Promise<string> => {
  try {
    const response = await sendMessageToServiceWorker({ type: 'GET_VERSION' });
    const versionResponse = response as { version?: string };
    return versionResponse.version || 'unknown';
  } catch (error) {
    logger.error('❌ Failed to get service worker version:', error);
    return 'unknown';
  }
};

/**
 * Enhanced update service worker with better coordination
 */
export const updateServiceWorkerCoordinated = async (registration: ServiceWorkerRegistration): Promise<void> => {
  if (!registration || !registration.waiting) {
    throw new Error('No service worker waiting to update');
  }

  logger.log('🚀 Starting coordinated service worker update...');

  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error('Service worker update timeout'));
    }, 10000); // 10 second timeout

    // Listen for the controlling change event
    const handleControllerChange = () => {
      clearTimeout(timeout);
      navigator.serviceWorker.removeEventListener('controllerchange', handleControllerChange);
      logger.log('✅ Service worker update completed successfully');
      resolve();
    };

    navigator.serviceWorker.addEventListener('controllerchange', handleControllerChange);

    // Tell the waiting service worker to skip waiting and become active
    registration.waiting!.postMessage({ type: 'SKIP_WAITING' });

    // Emit event for other parts of the app
    swEventEmitter.emit('update-started', { registration });
  });
};
