-- Migration: Create ai_usage_logs table for tracking AI API token usage and costs
-- Feature: AI Token Usage Tracking
-- Related: RepCue AI Assistant
-- Created: 2025-10-05
-- Author: Claude (RepCue AI Assistant)

-- ============================================================================
-- Table: ai_usage_logs
-- Purpose: Track token usage, costs, and metadata for all AI API calls
-- ============================================================================

CREATE TABLE ai_usage_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Request identification
  correlation_id text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- AI provider info
  provider text NOT NULL, -- 'mistral', 'anthropic', 'openai'
  model text NOT NULL, -- 'mistral-large-latest', 'claude-3-5-sonnet-20241022', etc.

  -- Token usage (from AI API response)
  input_tokens integer NOT NULL CHECK (input_tokens >= 0),
  output_tokens integer NOT NULL CHECK (output_tokens >= 0),
  total_tokens integer NOT NULL CHECK (total_tokens >= 0),

  -- Cost calculation (USD)
  input_cost_usd numeric(10, 6) NOT NULL CHECK (input_cost_usd >= 0),
  output_cost_usd numeric(10, 6) NOT NULL CHECK (output_cost_usd >= 0),
  total_cost_usd numeric(10, 6) NOT NULL CHECK (total_cost_usd >= 0),

  -- Request metadata
  request_type text DEFAULT 'workout_generation' NOT NULL,
  success boolean NOT NULL,
  error_code text,

  -- Performance
  processing_time_ms integer NOT NULL CHECK (processing_time_ms >= 0),

  -- Timestamps
  created_at timestamptz DEFAULT now() NOT NULL,

  -- Constraints
  CONSTRAINT ai_usage_logs_correlation_id_unique UNIQUE (correlation_id),
  CONSTRAINT ai_usage_logs_token_consistency CHECK (total_tokens = input_tokens + output_tokens)
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- Index for per-user queries
CREATE INDEX idx_ai_usage_logs_user_id ON ai_usage_logs(user_id);

-- Index for time-series queries (most recent first)
CREATE INDEX idx_ai_usage_logs_created_at ON ai_usage_logs(created_at DESC);

-- Index for provider comparison
CREATE INDEX idx_ai_usage_logs_provider ON ai_usage_logs(provider);

-- Index for filtering successful requests
CREATE INDEX idx_ai_usage_logs_success ON ai_usage_logs(success);

-- Composite index for date-range + provider queries
CREATE INDEX idx_ai_usage_logs_date_provider ON ai_usage_logs(created_at DESC, provider);

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE ai_usage_logs IS 'Tracks token usage and costs for all AI API calls in RepCue AI Assistant';
COMMENT ON COLUMN ai_usage_logs.id IS 'Primary key (UUID)';
COMMENT ON COLUMN ai_usage_logs.correlation_id IS 'Correlation ID from Edge Function request (matches logger output)';
COMMENT ON COLUMN ai_usage_logs.user_id IS 'User who made the request (FK to auth.users)';
COMMENT ON COLUMN ai_usage_logs.provider IS 'AI provider name (mistral, anthropic, openai)';
COMMENT ON COLUMN ai_usage_logs.model IS 'Specific model used (e.g., mistral-large-latest)';
COMMENT ON COLUMN ai_usage_logs.input_tokens IS 'Number of input tokens sent to AI (prompt + exercise catalog)';
COMMENT ON COLUMN ai_usage_logs.output_tokens IS 'Number of output tokens generated by AI (workout JSON)';
COMMENT ON COLUMN ai_usage_logs.total_tokens IS 'Total tokens (input + output)';
COMMENT ON COLUMN ai_usage_logs.input_cost_usd IS 'Cost of input tokens in USD';
COMMENT ON COLUMN ai_usage_logs.output_cost_usd IS 'Cost of output tokens in USD';
COMMENT ON COLUMN ai_usage_logs.total_cost_usd IS 'Total cost in USD (input + output)';
COMMENT ON COLUMN ai_usage_logs.request_type IS 'Type of AI request (workout_generation, future: exercise_recommendation, etc.)';
COMMENT ON COLUMN ai_usage_logs.success IS 'Whether the AI request succeeded';
COMMENT ON COLUMN ai_usage_logs.error_code IS 'Error code if request failed (NULL if success)';
COMMENT ON COLUMN ai_usage_logs.processing_time_ms IS 'Time taken by AI API call in milliseconds';
COMMENT ON COLUMN ai_usage_logs.created_at IS 'Timestamp when the request was made';

-- ============================================================================
-- Row-Level Security (RLS)
-- ============================================================================

-- Enable RLS on the table
ALTER TABLE ai_usage_logs ENABLE ROW LEVEL SECURITY;

-- Service role has full access (for Edge Function inserts and admin queries)
CREATE POLICY "Service role has full access to ai_usage_logs"
  ON ai_usage_logs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Users cannot access this table directly (admin-only access via service role)
-- No user-facing policies defined

-- ============================================================================
-- Verification Queries
-- ============================================================================

-- Verify table structure
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'ai_usage_logs'
-- ORDER BY ordinal_position;

-- Verify indexes
-- SELECT indexname, indexdef
-- FROM pg_indexes
-- WHERE tablename = 'ai_usage_logs';

-- Verify RLS policies
-- SELECT policyname, permissive, roles, cmd, qual, with_check
-- FROM pg_policies
-- WHERE tablename = 'ai_usage_logs';
