-- Migration: Add AI workout metadata fields to workouts table
-- Description: Adds fields to track AI-generated workouts and their generation parameters
-- Date: 2025-10-03
-- Feature: RepCue AI Assistant

-- Add AI workout metadata columns to workouts table
-- These fields are nullable for backward compatibility with existing workouts

ALTER TABLE workouts
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;

COMMENT ON COLUMN workouts.ai_generated IS 'Indicates whether this workout was generated by the AI Assistant';

ALTER TABLE workouts
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ;

COMMENT ON COLUMN workouts.generated_at IS 'Timestamp when the workout was generated by AI (ISO 8601 format)';

ALTER TABLE workouts
ADD COLUMN IF NOT EXISTS generation_params JSONB;

COMMENT ON COLUMN workouts.generation_params IS 'Parameters used for AI generation (goal, fitness level, training style, time availability) stored as JSON for future reference';

-- Create index for filtering AI-generated workouts
-- This improves query performance when filtering by ai_generated flag
CREATE INDEX IF NOT EXISTS idx_workouts_ai_generated
ON workouts(ai_generated)
WHERE ai_generated = true;

COMMENT ON INDEX idx_workouts_ai_generated IS 'Index for efficiently querying AI-generated workouts';

-- Create index on generated_at for sorting and filtering by generation date
CREATE INDEX IF NOT EXISTS idx_workouts_generated_at
ON workouts(generated_at)
WHERE generated_at IS NOT NULL;

COMMENT ON INDEX idx_workouts_generated_at IS 'Index for efficiently querying workouts by generation date';
