name: CI

on:
  push:
    branches: 
      - main
      - develop
      - 'feature/*'   # matches feature/foo (one level)
      - 'fixes/**'    # matches fixes/a or fixes/a/b (multi-level)
      - 'chores/**'

  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests (CI concise)
        run: npm run test:ci
      - name: i18n missing-keys scan
        run: npm run i18n:scan
      - name: Build
        run: npm run build
