name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Unit tests (non-interactive)
        run: npm run test:unit
      - name: i18n missing-keys scan
        run: npm run i18n:scan
      - name: Build
        run: npm run buildname: CI

on:
  push:
    branches: [ main, develop, '**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Test (if present)
        run: npm test --if-present

      - name: Build (if present)
        run: npm run build --if-present

      - name: Upload build artifact (if present)
        if: hashFiles('dist/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/**
            !dist/**/*.map
