name: CI

# Temporarily disabled CI
# on:
#   push:
#     branches: 
#       - main
#       - develop
#       - 'feature/*'   # matches feature/foo (one level)
#       - 'fixes/**'    # matches fixes/a or fixes/a/b (multi-level)
#       - 'chores/**'
# 
#   pull_request:
#     branches: [ develop, main ]

# Manual trigger only while CI is disabled
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Unit tests (CI concise)
        run: pnpm test:ci
      - name: i18n missing-keys scan
        run: pnpm i18n:scan
      - name: Build
        run: pnpm build
